version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: libert-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0110
      POSTGRES_DB: libertdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libert-server-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: libertdb
      DB_USER: postgres
      DB_PASSWORD: 0110

volumes:
  postgres_data:
