services:
  db:
    image: postgres:latest
    container_name: libert-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0110
      POSTGRES_DB: libertdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - libert-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-libert-server-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - libert-network

volumes:
  postgres_data:

networks:
  libert-network:
